### ISSUE TITLE
Module build failed: Error: Couldn't find preset "./.babelrc.js" relative to directory "$path\\node_modules\\react-virtualized"

### ISSUE THREAD

**Issue by kirillk-tf** [bvaughn/react-virtualized#1284]
ERROR in ./~/react-virtualized/dist/commonjs/List/index.js
Module build failed: Error: Couldn't find preset "./.babelrc.js" relative to directory "D:\\test\\node_modules\\react-virtualized"
    at D:\test\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (D:\test\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (D:\test\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (D:\test\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (D:\test\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (D:\test\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (D:\test\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (D:\test\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (D:\test\node_modules\babel-loader\lib\index.js:46:20)
    at Object.module.exports (D:\test\node_modules\babel-loader\lib\index.js:163:20)
 @ ./src/app/modules/account/containers/Messages.jsx 27:12-59
 @ ./src/app/modules/account/routes.js
 @ ./src/app/routes.js
 @ ./src/app/index.jsx

**Comment by kirillk-tf** [comment]
BABEL file:

```
{
    "plugins": 
    [
        "react-hot-loader/babel",
        "transform-decorators-legacy",
        "transform-es2015-literals"
    ],

    "ignore" : {
        "static_data/jquery/**"
    },

    "presets": 
    [
        "es2015",
        "stage-0",
        "react"
    ],

    "env": 
    {
        "production": 
        {
            "presets":
            [
                "react-optimize"
            ]
        },

        "development": 
        {
            "plugins": 
            [
                "transform-react-jsx-source"
            ]
        }
    }
}
```

**Comment by wuweiweiwu** [comment]
please see https://github.com/bvaughn/react-virtualized/issues/1112
