### ISSUE TITLE
Support server-side rendering (undefined 'window' and 'document')

### ISSUE THREAD

**Issue by oyeanuj** [bvaughn/react-virtualized#41]
Hi @bvaughn! I ran into this error while trying out AutoSizer component for the first time. I was trying this originally with SSR on but even with no SSR, I still see the same issue. 

I am probably making a n00b mistake but any pointers would be much appreciated!

Package version: "react-virtualized": "^2.6.1"

```
[piping] can't execute file: /Users/anuj/Github/shuffle-web/bin/server.js
[1] [piping] error given was: ReferenceError: document is not defined
[1]     at Object.exports.__esModule (/Users/oyeanuj/Github/helloworld/node_modules/react-virtualized/dist/react-virtualized.js:280:20)
[1]     at __webpack_require__ (/Users/oyeanuj/Github/helloworld/node_modules/react-virtualized/dist/react-virtualized.js:30:30)
[1]     at Object.module.exports (/Users/oyeanuj/Github/helloworld/node_modules/react-virtualized/dist/react-virtualized.js:158:35)
[1]     at __webpack_require__ (/Users/oyeanuj/Github/helloworld/node_modules/react-virtualized/dist/react-virtualized.js:30:30)
[1]     at Object.defineProperty.value (/Users/oyeanuj/Github/helloworld/node_modules/react-virtualized/dist/react-virtualized.js:120:20)
[1]     at __webpack_require__ (/Users/oyeanuj/Github/helloworld/node_modules/react-virtualized/dist/react-virtualized.js:30:30)
[1]     at Object.defineProperty.value (/Users/oyeanuj/Github/helloworld/node_modules/react-virtualized/dist/react-virtualized.js:63:19)
[1]     at __webpack_require__ (/Users/oyeanuj/Github/helloworld/node_modules/react-virtualized/dist/react-virtualized.js:30:30)
[1]     at Object.defineProperty.value (/Users/oyeanuj/Github/helloworld/node_modules/react-virtualized/dist/react-virtualized.js:50:18)
[1]     at /Users/anuj/Github/helloworld/node_modules/react-virtualized/dist/react-virtualized.js:53:10
```

**Comment by bvaughn** [comment]
Hm... this isn't a server-rendered page, by chance?

Afraid I'll need more context to be of much help. Any chance you could post a Plunker/Jsbin?

**Comment by bvaughn** [comment]
I just published version 2.6.2 with a check for `document`. Let me know if this resolves the issue for you? (Reopen this issue if it doesn't.)

**Comment by oyeanuj** [comment]
Re-opening as per our conversation, now getting the following error:

```
[1] [piping] error given was: TypeError: Cannot read property 'requestAnimationFrame' of undefined
[1]     at /node_modules/react-virtualized/dist/react-virtualized.js:302:23
[1]     at Object.exports.__esModule (/node_modules/react-virtualized/dist/react-virtualized.js:308:6)
```

**Comment by frankleng** [comment]
@bvaughn thanks for taking this on.
I've been working around it by injecting the react-virtualized components in componentDidMount.

What's your solution to this? return if window === undefined?

**Comment by bvaughn** [comment]
No problem. That's a nice work-around in the meanwhile.

I'm actually hoping I can switch to another element resize library that properly handles this (because I don't really want to reinvent the wheel there- that isn't part of the virtualization domain really). We'll see. :)

**Comment by oyeanuj** [comment]
> I've been working around it by injecting the react-virtualized components in componentDidMount.
@frankleng I was thinking of setting a flag in `componentDidMount` which will allow `react-virtualized` to be rendered. Is that what you were also saying by 'injecting component in componentDidMount'?

**Comment by frankleng** [comment]
@bvaughn sounds good. was also thinking about doing a prerender a few rows on server to accelerate mobile rendering. might put a PR in once I have more time.

**Comment by bvaughn** [comment]
Happy to accept PRs :)

**Comment by frankleng** [comment]
@oyeanuj something like that. 
my render method is doing ```return this.content```
```this.content``` by default is an ajax spinner
in componentDidMount() I call a method that does
```
this.content = (<AutoSizer />);
this.forceUpdate();
```
reason I didn't simply set a flag is because I have to import react-virtualized components inside that client-side render method. If you load it at the class level, it'll complain about ```document```

**Comment by bvaughn** [comment]
Afraid the rabbit hole goes deeper than I feared.

I patched the window/document issue WRT the resize detection only to get burned by the [Webpack style-loader](https://github.com/webpack/style-loader/blob/master/addStyles.js#L14).

**Comment by oyeanuj** [comment]
@bvaughn I can try that. 

Another thought: Would it make sense that the the `<ChildComponent ..` in `AutoSizer.js` is loaded on `componentDidMount` instead of `render` to avoid the problem?

**Comment by bvaughn** [comment]
I have an idea that's showing some promise even thought it's a little weird. Basically I'm deferring the import of styles and element-resize code until `componentDidMount` (so that I'm sure we're actually on the client) and then re-rendering.

This feels a little dirty though. Thoughts?

**Comment by bvaughn** [comment]
@oyeanuj @frankleng Please check out release 2.7.5. I am now deferring the element resize until `componentDidMount` which should enable server-side rendering.

**Comment by bvaughn** [comment]
I am going to close this issue for now as I _think_ it has been resolved. Please reach out to me on Discord and/or reopen it if you are still having troubles. :)

**Comment by bvaughn** [comment]
FYI I've created issue #48 to (hopefully) further simplify things.

**Comment by DeDuckProject** [comment]
This seems to re-occur in `9.10.0`:

```
myProj/node_modules/react-virtualized/dist/commonjs/utils/animationFrame.js:21
var request = win.requestAnimationFrame || win.webkitRequestAnimationFrame || win.mozRequestAnimationFrame || win.oRequestAnimationFrame || win.msRequestAnimationFrame || function (callback) {
                 ^
TypeError: Cannot read property 'requestAnimationFrame' of undefined
```

in `9.9.0` all is ok.
I am using `Grid`

@bvaughn
