### ISSUE TITLE
Issue with PostCSS config

### ISSUE THREAD

**Issue by Pszek** [bvaughn/react-virtualized#735]
Thanks for creating react-virtualized! :)

During a build process (with Docker) I stumbled upon the below issue:

```ERROR in /tmp/~/react-virtualized/styles.css
Module build failed: ModuleBuildError: Module build failed: Error: No PostCSS Config found in: /tmp/node_modules/react-virtualized
    at /tmp/node_modules/postcss-load-config/index.js:51:26
    at <anonymous>
    at runLoaders (/tmp/node_modules/webpack/lib/NormalModule.js:192:19)
    at /tmp/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /tmp/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/tmp/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (/tmp/node_modules/postcss-loader/lib/index.js:176:71)
    at <anonymous>
 @ ./js/components/VirtualList/index.js 13:0-39
 @ ./js/components/ProductsList/index.js
 @ ./js/startup/clientGlobals.js
 @ multi ./js/startup/clientGlobals

ERROR in /tmp/~/react-virtualized/styles.css
Module build failed: ModuleBuildError: Module build failed: Error: No PostCSS Config found in: /tmp/node_modules/react-virtualized
    at /tmp/node_modules/postcss-load-config/index.js:51:26
    at <anonymous>
    at runLoaders (/tmp/node_modules/webpack/lib/NormalModule.js:192:19)
    at /tmp/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /tmp/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/tmp/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (/tmp/node_modules/postcss-loader/lib/index.js:176:71)
    at <anonymous>
```

packages versions:
```
"postcss-loader": "^2.0.6",
"react (DOM)": "^15.6.1",
"react-virtualized": "^9.9.0",
"webpack": "^2.6.1"
```

I realise this could be an issue with PostCSS Loader, but it is the only package getting that error. I tried to found similar issues but to no avail. If you have some ideas about causes of that problem or how to solve it please share it with me :) .

**Comment by TrySound** [comment]
@Pszek This is an issue with postcss-loader. Open it there.

**Comment by bvaughn** [comment]
Hi @Pszek,

Thanks for the kind words. 😄 

This issue has nothing to do with react-virtualized. All this project does is include a CSS file in its NPM bundle. Nothing special there. Sounds like your postcss-loader isn't configured correctly to exclude `node_modules`. I'd start looking there.

**Comment by Pszek** [comment]
@bvaughn Thanks, it seems that was it!

**Comment by bvaughn** [comment]
No problem 😄
